targets:
  - name: lessons
    sources:
      - /public/lesson/en/*.md
    file: /public/lesson/en/%language%.strings
    format: macosx
files:
  - source: /public/lesson/en/*.md
    ignore:
      - bankless-archetypes.md
      - going-bankless.md
      - kudos-testing.md
      - conceptos-basicos-de-blockchain.md
    translation: /public/lesson/%two_letters_code%/%original_file_name%
